version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin       # Fixed typo from POSTRES_USER to POSTGRES_USER
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/postgres
      PORT: 5000
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: {}  # Ensure this is a valid empty mapping
    depends_on:
      - backend

volumes:
  postgres_data:
